name: Build and Package TLA Proof Manager
on:
  push:
    branches:
      - main
jobs:
    test:
        name: Build TLAPS installer and test it
        runs-on: ${{ matrix.operating-system }}
        strategy:
          matrix:
            operating-system:
              - macos-latest,
              - ubuntu-latest
            ocaml-compiler:
              - '0'
              - '1'
        steps:
            - name: Install deps
              if: matrix.operating-system == 'ubuntu-latest'
              run: |
                sudo apt-get update
                sudo apt-get install --yes time
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.12'
            - uses: actions/checkout@v3
            - name: Get OCaml version
              run: |
                INDEX=${{ matrix.ocaml-compiler }}
                OCAML_VERSION=\
                `python .github/workflows/ocaml_versions.py $INDEX`
                echo "OCAML_VERSION=$OCAML_VERSION" \
                >> $GITHUB_ENV
                echo "OCAML_VERSION = $OCAML_VERSION"
            - uses: ocaml/setup-ocaml@v2
              with:
                ocaml-compiler: ${{ env.OCAML_VERSION }}
            - name: Build TLAPS installer
              run: |
                eval $(opam env)
                opam install ./ --deps-only --yes
                make
                make release
            - name: Run tests
              if: >-
                matrix.operating-system == 'ubuntu-latest' &&
                matrix.ocaml-compiler == '1'
              run: |
                eval $(opam env)
                set +e
                make test
                TEST_RESULT=$?
                cat _build/default/test/tests.log
                exit $TEST_RESULT
            - name: Trigger run of tlaplus/examples CI
              if: matrix.ocaml-compiler == '1'
              uses: peter-evans/repository-dispatch@v2
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  repository: tlaplus/examples
                  event-type: tlapm-dispatch

